apiVersion: v1
kind: ConfigMap
metadata:
  name: lynq-app-backend-config
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-app-backend
data:
{{- range $key, $value := .Values.lynq_app_backend.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
