apiVersion: v1
kind: ConfigMap
metadata:
  name: lynq-file-storage-config
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-file-storage
data:
{{- range $key, $value := .Values.lynq_file_storage.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
