sonar.organization=lynq-matlock
sonar.projectKey=MatLock_UdeSA-lynq
sonar.projectName=UdeSA-lynq
sonar.sources=.
sonar.java.binaries=lynq-iam/target/classes,lynq-app-backend/target/classes
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/*.min.js,**/*.min.css
