# Prod (AWS EKS). Terraform creates the VPC, the EKS cluster, the load balancer
# controller, the namespace, the external Secrets, S3, SNS, SQS, the IAM users
# and the helm_release. MySQL and Redis are external: point db_host/redis_host
# at them and allow the nat_public_ip output on both.
aws_region = "us-east-1"
namespace  = "lynq-prod-namespace"

vpc_cidr = "10.0.0.0/16"

db_host    = "REPLACE_DB_HOST"
db_port    = 3306
redis_host = "REPLACE_REDIS_HOST"
redis_port = 6379

# EKS control plane + EC2 worker nodes, in the private subnets of the VPC above.
eks_node_instance_type = "t3.medium"
eks_node_capacity_type = "ON_DEMAND"
eks_node_desired_size  = 2

# Public API host + Cloudflare DNS. Terraform creates the ACM cert, validates it
# via a Cloudflare DNS record, and points this host at the ALB.
ingress_host       = "api.lynqoficial.com"
cloudflare_zone_id = "REPLACE_CF_ZONE_ID"

s3_bucket_name = "REPLACE_BUCKET_NAME"

# lynq-llm and lynq-agent run on Bedrock in prod (LLM_PROVIDER=bedrock in
# k8s_values-prod.yaml). Both models must be enabled in this region.
bedrock_model_id       = "amazon.nova-lite-v1:0"
agent_bedrock_model_id = "amazon.nova-pro-v1:0"
bedrock_region         = "us-east-1"

# Both Bedrock IAM users may invoke every model here (plus the two above).
bedrock_invocable_model_ids = ["amazon.nova-lite-v1:0", "amazon.nova-pro-v1:0"]

# Only the app frontend uploads and downloads against the pre-signed URLs.
s3_cors_allowed_origins = ["https://app.lynqoficial.com"]

# -------------------------------------------------------------------------
# Secrets: DO NOT put real values here (this file is committed). Provide them
# as environment variables before applying:
#
#   TF_VAR_cloudflare_api_token
#   TF_VAR_dockerhub_token
#   TF_VAR_db_username
#   TF_VAR_db_password
#   TF_VAR_redis_username        (only if Redis requires auth)
#   TF_VAR_redis_password        (only if Redis requires auth)
#
# The JWT secret, the internal token and every AWS access key the services use
# are generated by Terraform and written straight into their Secrets.
# -------------------------------------------------------------------------
