apiVersion: v1
kind: Service
metadata:
  name: lynq-agent-service
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-agent
spec:
  type: ClusterIP
  selector:
    app: lynq-agent
  ports:
    - name: http
      port: 8090
      targetPort: http
