{{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: lynq-ml-secret
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-ml
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.credentials.bedrock.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.credentials.bedrock.secretAccessKey | quote }}
{{- end }}
