{{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: lynq-bff-secret
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-bff
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.credentials.jwt.secret | quote }}
{{- end }}
