{{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: lynq-app-backend-secret
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-app-backend
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.credentials.db.username | quote }}
  DB_PASSWORD: {{ .Values.credentials.db.password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.credentials.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.credentials.aws.secretAccessKey | quote }}
{{- end }}
