{{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: lynq-iam-secret
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-iam
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.credentials.db.username | quote }}
  DB_PASSWORD: {{ .Values.credentials.db.password | quote }}
  REDIS_USERNAME: {{ .Values.credentials.redis.username | quote }}
  REDIS_PASSWORD: {{ .Values.credentials.redis.password | quote }}
  JWT_SECRET: {{ .Values.credentials.jwt.secret | quote }}
{{- end }}
