{{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: lynq-ml-secret
  namespace: lynq-{{ .Values.k8s_namespace }}-namespace
  labels:
    app: lynq-ml
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.credentials.openai.apiKey | quote }}
{{- end }}
