output "namespace" {
  description = "Namespace the release was deployed into."
  value       = var.namespace
}

output "release_name" {
  description = "Helm release name."
  value       = helm_release.lynq.name
}

output "release_status" {
  description = "Status of the Helm release."
  value       = helm_release.lynq.status
}

output "chart_version" {
  description = "Version of the deployed chart."
  value       = helm_release.lynq.version
}

output "ingress_host" {
  description = "Public host of the gateway (lynq-bff) in prod — every call enters through it."
  value       = var.ingress_host
}

output "s3_bucket_name" {
  description = "Name of the S3 bucket created by Terraform."
  value       = aws_s3_bucket.lynq.bucket
}

output "vpc_id" {
  description = "Id of the VPC Terraform created for the cluster."
  value       = aws_vpc.lynq.id
}

output "nat_public_ip" {
  description = "Public IP every pod leaves the VPC through. Allow it on the external MySQL and Redis."
  value       = aws_eip.nat.public_ip
}

output "file_storage_s3_access_key_id" {
  description = "Access key id of the S3-only IAM user consumed by lynq-file-storage (the secret lives only in state / the k8s Secret)."
  value       = aws_iam_access_key.backend_s3.id
}

output "domain_events_topic_arn" {
  description = "ARN of the SNS topic lynq-app-backend publishes its domain events to."
  value       = aws_sns_topic.domain_events.arn
}

output "backend_sns_access_key_id" {
  description = "Access key id of the publish-only IAM user consumed by lynq-app-backend (the secret lives only in state / the k8s Secret)."
  value       = aws_iam_access_key.backend_sns.id
}

output "llm_bedrock_access_key_id" {
  description = "Access key id of the Bedrock-only IAM user consumed by lynq-llm (the secret lives only in state / the k8s Secret)."
  value       = aws_iam_access_key.llm_bedrock.id
}

output "agent_bedrock_access_key_id" {
  description = "Access key id of the Bedrock-only IAM user consumed by lynq-agent (the secret lives only in state / the k8s Secret)."
  value       = aws_iam_access_key.agent_bedrock.id
}

output "internal_token" {
  description = "Shared secret of the /internal/** routes, generated by Terraform. Read it with: terraform output -raw internal_token."
  value       = random_password.internal_token.result
  sensitive   = true
}

output "analytics_events_queue_url" {
  description = "URL of the SQS queue lynq-analytics consumes, subscribed to the domain events topic."
  value       = aws_sqs_queue.analytics_events.url
}

output "analytics_sqs_access_key_id" {
  description = "Access key id of the consume-only IAM user used by lynq-analytics (the secret lives only in state / the k8s Secret)."
  value       = aws_iam_access_key.analytics_sqs.id
}

output "eks_cluster_name" {
  description = "EKS cluster name. Feed it to: aws eks update-kubeconfig --name <this> --region <aws_region>."
  value       = aws_eks_cluster.lynq.name
}

output "eks_cluster_endpoint" {
  description = "Kubernetes API endpoint of the EKS cluster."
  value       = aws_eks_cluster.lynq.endpoint
}

output "eks_oidc_provider_arn" {
  description = "OIDC provider ARN of the cluster. Use it to grant IRSA roles to ServiceAccounts (replaces the static access keys)."
  value       = aws_iam_openid_connect_provider.eks.arn
}
