# ---------------------------------------------------------------------------
# S3 bucket for lynq-file-storage — the only service that talks to S3. It holds
# every platform file (profile images, company logos, résumé PDFs) and serves
# them through pre-signed URLs.
# (Local uses LocalStack instead, handled entirely by Helm.)
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "lynq" {
  bucket = var.s3_bucket_name
}

# Keep the bucket private — access is granted through the pre-signed URLs
# lynq-file-storage issues, not via public ACLs/policies.
resource "aws_s3_bucket_public_access_block" "lynq" {
  bucket                  = aws_s3_bucket.lynq.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Enforce HTTPS-only access: deny any request made over plain HTTP. This is a
# Deny statement (not a public grant), so it coexists with the public-access
# block above.
data "aws_iam_policy_document" "lynq_https_only" {
  statement {
    sid    = "DenyInsecureTransport"
    effect = "Deny"

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.lynq.arn,
      "${aws_s3_bucket.lynq.arn}/*",
    ]

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "lynq" {
  bucket     = aws_s3_bucket.lynq.id
  policy     = data.aws_iam_policy_document.lynq_https_only.json
  depends_on = [aws_s3_bucket_public_access_block.lynq]
}

# CORS so the browser can PUT/GET directly against the pre-signed URLs
# lynq-file-storage hands out.
resource "aws_s3_bucket_cors_configuration" "lynq" {
  bucket = aws_s3_bucket.lynq.id

  cors_rule {
    allowed_origins = var.s3_cors_allowed_origins
    allowed_methods = ["GET", "PUT", "HEAD"]
    allowed_headers = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# ---------------------------------------------------------------------------
# Server access logging. Logs are delivered to a dedicated, private log bucket
# (a log bucket does not log itself, to avoid a delivery loop).
# ---------------------------------------------------------------------------
data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "lynq_logs" {
  bucket = "${var.s3_bucket_name}-logs"
}

resource "aws_s3_bucket_public_access_block" "lynq_logs" {
  bucket                  = aws_s3_bucket.lynq_logs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Allow the S3 log delivery service to write access logs into the log bucket.
data "aws_iam_policy_document" "lynq_logs" {
  statement {
    sid    = "S3ServerAccessLogsPolicy"
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["logging.s3.amazonaws.com"]
    }

    actions   = ["s3:PutObject"]
    resources = ["${aws_s3_bucket.lynq_logs.arn}/*"]

    condition {
      test     = "ArnLike"
      variable = "aws:SourceArn"
      values   = [aws_s3_bucket.lynq.arn]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values   = [data.aws_caller_identity.current.account_id]
    }
  }
}

resource "aws_s3_bucket_policy" "lynq_logs" {
  bucket     = aws_s3_bucket.lynq_logs.id
  policy     = data.aws_iam_policy_document.lynq_logs.json
  depends_on = [aws_s3_bucket_public_access_block.lynq_logs]
}

resource "aws_s3_bucket_logging" "lynq" {
  bucket        = aws_s3_bucket.lynq.id
  target_bucket = aws_s3_bucket.lynq_logs.id
  target_prefix = "s3-access-logs/"
}

# ---------------------------------------------------------------------------
# Least-privilege IAM user for lynq-file-storage: access to THIS bucket only.
# Its access key is generated by Terraform and wired straight into the
# lynq-file-storage Secret (see main.tf), so no AWS keys are set by hand.
#
# The resource addresses and the IAM user name below still say "backend": they
# date from when lynq-app-backend owned the bucket. They are deliberately left
# alone — the user name is ForceNew, so renaming it would replace the user and
# rotate the access key, and the running pod would keep using the deleted key
# until it restarts. Only the consumer changed (see kubernetes_secret.file_storage).
# ---------------------------------------------------------------------------
resource "aws_iam_user" "backend_s3" {
  name = "lynq-backend-s3"
}

data "aws_iam_policy_document" "backend_s3" {
  statement {
    sid       = "BucketObjects"
    effect    = "Allow"
    actions   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
    resources = ["${aws_s3_bucket.lynq.arn}/*"]
  }

  statement {
    sid       = "BucketList"
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_bucket.lynq.arn]
  }
}

resource "aws_iam_user_policy" "backend_s3" {
  name   = "lynq-backend-s3-access"
  user   = aws_iam_user.backend_s3.name
  policy = data.aws_iam_policy_document.backend_s3.json
}

resource "aws_iam_access_key" "backend_s3" {
  user = aws_iam_user.backend_s3.name
}
