# ---------------------------------------------------------------------------
# S3 bucket for the backend (profile images via pre-signed uploads).
# (Local uses LocalStack instead, handled entirely by Helm.)
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "lynq" {
  bucket = var.s3_bucket_name
}

# Keep the bucket private — access is granted through the pre-signed URLs the
# backend issues, not via public ACLs/policies.
resource "aws_s3_bucket_public_access_block" "lynq" {
  bucket                  = aws_s3_bucket.lynq.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# CORS so the browser can PUT/GET directly against the pre-signed URLs the
# backend hands out.
resource "aws_s3_bucket_cors_configuration" "lynq" {
  bucket = aws_s3_bucket.lynq.id

  cors_rule {
    allowed_origins = var.s3_cors_allowed_origins
    allowed_methods = ["GET", "PUT", "HEAD"]
    allowed_headers = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# ---------------------------------------------------------------------------
# Least-privilege IAM user for the backend: access to THIS bucket only. Its
# access key is generated by Terraform and wired straight into the backend
# Secret (see main.tf), so no AWS keys are set by hand.
# ---------------------------------------------------------------------------
resource "aws_iam_user" "backend_s3" {
  name = "lynq-backend-s3"
}

data "aws_iam_policy_document" "backend_s3" {
  statement {
    sid       = "BucketObjects"
    effect    = "Allow"
    actions   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
    resources = ["${aws_s3_bucket.lynq.arn}/*"]
  }

  statement {
    sid       = "BucketList"
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_bucket.lynq.arn]
  }
}

resource "aws_iam_user_policy" "backend_s3" {
  name   = "lynq-backend-s3-access"
  user   = aws_iam_user.backend_s3.name
  policy = data.aws_iam_policy_document.backend_s3.json
}

resource "aws_iam_access_key" "backend_s3" {
  user = aws_iam_user.backend_s3.name
}
